### ISSUE TITLE
Model to match Department objects to the click event on the Menu

### ISSUE THREAD

**Issue by RyanDawkins** [TeamGreenMobileApp2015/HotelApp#13]
There's a few ways we can do this...
- We can pass the menu item that is clicked to the CalendarViewController.
  - This lightens the load of data being passed between ViewControllers
- Get all of the departments onload, then pass the department to the CalendarViewController
  - By default it would lookup all (overview mode)
  - It would also make it easier to query for all tasks by department

Either way this needs to get done. We can create the CalendarViewController storyboard before this if we want however.

This is a subissue of #8

**Comment by divergentnate** [comment]
Maybe I am confused but isn't this already done? The prepareForSegue method in the ViewController class detects the icon pressed using a segue.identifier and sends data to the CalanderViewController. If we need to send more data I can add that to the code I already wrote to do this. Sorry if I didn't understand in advance.

**Comment by nathan-hoover** [comment]
Maybe I am confused but isn't this already done? The prepareForSegue method in the ViewController class detects the icon pressed using a segue.identifier and sends data to the CalanderViewController. If we need to send more data I can add that to the code I already wrote to do this. Sorry if I didn't understand in advance.

**Comment by RyanDawkins** [comment]
This is done now.
