### ISSUE TITLE
User Creation Domain Logic

### ISSUE THREAD

**Issue by RyanDawkins** [TeamGreenMobileApp2015/HotelApp#4]
- Create a user with email/password
- Tell manager to manually them the password/username

**Comment by RyanDawkins** [comment]
This can be done through Parse... We could just say make them call support for a username/password?

**Comment by jeffmshepherd** [comment]
I may work on this part today or tomorrow. Do we want to worry about roles at this point? If so, we could make standard users and then administrators. Standard users can complete tasks and admins can create tasks, complete tasks, delete standard users and promote standard users to admins. I'll have to play around and see how much of this can be controlled through the app. Thoughts?

**Comment by RyanDawkins** [comment]
@jeffmshepherd No don't work on this. If anything this will be the absolute LAST completed feature. It's nonessential and we don't need to add any complexity to the application before we have it finished.
