### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by RyanDawkins** [TeamGreenMobileApp2015/HotelApp#8]
![screen shot 2015-10-20 at 4 09 00 pm](https://cloud.githubusercontent.com/assets/1816072/10621161/9f84576e-7744-11e5-9261-1278db8e7abe.png)

**Comment by RyanDawkins** [comment]
I've started on creating this.. Many failed attempts by me with auto layout. See commit: https://github.com/TeamGreenMobileApp2015/HotelApp/commit/b95f05410ed9c828ec3e43b0f01748b88b24a590

**Comment by RyanDawkins** [comment]
@divergentnate and I have basically created the basic functionality for this.

I'll create some subissues for this.

**Comment by jeffmshepherd** [comment]
Would it help to ask the UI team to send the button images in the same size?

**Comment by nathan-hoover** [comment]
If we could get them to do that it would be nice. If its to much of a hassle just tell me and I will make them all matching sizes/resolution.

**Comment by RyanDawkins** [comment]
I'll email Kailey.

**Comment by RyanDawkins** [comment]
The images can be accessed in the dropbox link I gave you guys before.

**Comment by nathan-hoover** [comment]
I will be apply the new image and constraints.

**Comment by nathan-hoover** [comment]
I finished updating it using completely new constraints and design implementation. It look just like the design teams sketch and works on devices of 4 inches (iPhone 5)  and above. I will close this issue now. If anyone finds any problems please make a new issue and assign it to me.

**Comment by nathan-hoover** [comment]
The menu on multiple screen sizes
<img width="533" alt="screen shot 2015-11-20 at 9 25 12 pm" src="https://cloud.githubusercontent.com/assets/2775889/11316453/3c39a50a-8fcd-11e5-8e41-dbbde99f4cc0.png">

**Comment by nathan-hoover** [comment]
What it looks like in the simulator (iPhone 6)
<img width="395" alt="screen shot 2015-11-20 at 9 35 34 pm" src="https://cloud.githubusercontent.com/assets/2775889/11316487/abe858f0-8fce-11e5-9fa0-821b371bd023.png">

**Comment by RyanDawkins** [comment]
Good job.
